name: Daily Commit

on:
  schedule:
    - cron: '30 3 * * *'  # Runs daily at 03:30 UTC (adjust as needed)
  workflow_dispatch:       # Allows manual trigger for testing

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add a new commit (22f3002760@ds.study.iitm.ac.in)
        run: |
          echo "Commit made on $(date -u)" >> daily.log
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily.log
          git commit -m "Daily commit on $(date -u)"
          git push
